### ISSUE TITLE
Bunch of System.FormatExceptions when trying to run this.

### ISSUE THREAD

**Issue by PJB3005** [headswe/hqxdmi#2]
```
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Single.Parse(String s)
   at SS13to64x.DMI.DmiImage.GetIntList(String dequeue) in C:\Users\Simon\Documents\SS13 Repos\hqxdmi\SS13to64x\DMI\DMIimage.cs:line 108
   at SS13to64x.DMI.DmiImage.ReadState(String name, Queue`1 lines) in C:\Users\Simon\Documents\SS13 Repos\hqxdmi\SS13to64x\DMI\DMIimage.cs:line 95
   at SS13to64x.DMI.DmiImage..ctor(String file) in C:\Users\Simon\Documents\SS13 Repos\hqxdmi\SS13to64x\DMI\DMIimage.cs:line 46
   at SS13to64x.Program.ExtractDMI(String input, String outPath, String file) in C:\Users\Simon\Documents\SS13 Repos\hqxdmi\SS13to64x\Program.cs:line 188
```

**Comment by PJB3005** [comment]
After digging into this I've determined it's because of my computer's cultural settings.

Great.

**Comment by PJB3005** [comment]
https://stackoverflow.com/questions/1014535/float-parse-doesnt-work-the-way-i-wanted

**Comment by headswe** [comment]
Float parse tweaked to use invariantculture.
